# cleans the build artifacts
clean:
	rm -rf dist/*

# build the bundle to /dist
build: clean
	npm run build

# install the chaos-auth package
install VERSION:
	npm install ~/packages/chaos-auth-{{ VERSION }}.tar

# serve demo app locally
watch:
	npm run serve

# watch and deploy on update
serve:
	find ./components | entr -s 'npm run build && cp dist/index.modern.js ../assets/js/app/app.modern.js'

# run all tests
test:
	npm run test

# run all tests in watch mode
testwatch:
	npm run testwatch

# deploys the app bundle for Hugo to pick up in theme/assets/js/app
deploy: build
	cp dist/index.modern.js /Users/alexbilson/source/chaos-theme/assets/js/app/app.modern.js

hugo:
	find ./components | entr -s 'podman run -it --rm \
	-p 1313:1313 \
	-v /Users/alexbilson/source/chaos-content:/mnt/hugo/content \
	-v /Users/alexbilson/source/chaos-theme:/mnt/hugo/themes/chaos \
	--name hugo \
	acbilson/hugo:latest'


# launches a tmux session with everything I need to interactively develop
develop:
	tmux new-session -s theme -n watch -d   'just watch';
	tmux new-window  -t theme:1 -n hugo    'just hugo';
	tmux new-window  -t theme:2 -n serve    'just serve';
	tmux new-window  -t theme:3 -n micropub 'cd ~/source/chaos-micropub; just start';
	tmux new-window  -t theme:4 -n edit     'nvim index.ts';
	tmux new-window  -t theme:5 -n test     'nvim testwatch';
	tmux attach
