# build the bundle to /dist
build:
	npm run build

# install the chaos-auth package
install VERSION:
	npm install ~/packages/chaos-auth-{{ VERSION }}.tar

# watch and deploy on update
serve:
	find ./src | entr -s 'npm run build && cp dist/app.modern.js ../assets/js/app/'

# deploys the app bundle for Hugo to pick up in theme/assets/js/app
deploy: build
	cp dist/app.modern.js /Users/alexbilson/source/chaos-theme/assets/js/app
